title: Huanliang Chen's Homepage
page-top-title: Huanliang Chen
top-section-bg-text: Hi! Welcome to my personal page.
home-subtitle: Huanliang Chen&ensp;|&ensp;陈焕亮
copyright-text: '&copy; Huanliang Chen 2025-Present. All Rights Reserved.'
